### PR TITLE
RabbitMQ 2.1.1

### PR DESCRIPTION
**Pull request by leemhenson**
Hi,

As requested, I've rebased the commits from my previous merge request onto ezmobius/master.

Cheers
Lee

### CODE REVIEW

**Comment by roidrage** [comment]
Is there a reason you've removed :exclusive => true from the mapper? Was support for that removed in a newer version of RabbitMQ? I'd love to merge these patches, but they seem to fix some problems not necessarily all of them, as declaration of :durable => true doesn't seem to be fully consistent yet. I want to understand the changes before I merge them.

**Comment by leemhenson** [comment]
Ok, so it breaks down like this:

1) Never used RabbitMQ before
2) Never used Nanite before

So I'm like someone stumbling around in the dark control room of a power station throwing switches left, right and centre in the hope that one of them turns on the lights. I appear to have turned the lights on, but I might have accidentally stuck a plutonium rod in a reactor somewhere at the same time. In other words, I've been trying combinations of settings and found some that work and as far as I can see, that's an improvement on "not working at all" which is the situation for 2.1.1 on ezmobius/master as it stands at the moment. If I've mucked something else up along the way, I apologise!

**Comment by roidrage** [comment]
I didn't say you've mucked up, just wanted to know the whole setting, that's cool. I'll look through them, and test the things for a little bit before I merge them.

**Comment by leemhenson** [comment]
Groovy. Btw is the mapper_rework branch in a usable, stable-ish state? I'd rather be learning on the code that is most current, rather than the branch that is going to be made obsolete in the near future.

**Comment by roidrage** [comment]
I'm currently testing it. Things are looking good so far. It's not production ready, and will be subject for removal of features. Follow the mailing list, I'll give heads up over there on the status.

**Comment by roidrage** [comment]
These changes were already included with an earlier pull request, see #22, just merged them into master, thanks!

**Pull request closed without merging**
